name: Bicep CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  bicep-validation:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Install Azure CLI (safe method)
      - name: Install Azure CLI
        run: |
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

      # Install Bicep
      - name: Install Bicep
        run: az bicep install

      # -------------------------
      # LINT (only /bicep folder)
      # -------------------------
      - name: Lint Bicep files
        run: |
          echo "Linting production Bicep files..."
          find ./bicep -type f -name "*.bicep" -exec az bicep lint --file {} \;

      # -------------------------
      # AZURE LOGIN
      # -------------------------
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set Azure Subscription
        run: az account set --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # -------------------------
      # VALIDATE
      # -------------------------
      - name: Validate Bicep deployment
        run: |
         az deployment group validate \
          --resource-group ${{ secrets.AZURE_RG }} \
          --template-file bicep/main.bicep \
          --parameters @bicep/parameters/dev.parameters.json

      # -------------------------
      # WHAT-IF
      # -------------------------

      - name: What-If deployment
        run: |
          az deployment group what-if \
          --resource-group ${{ secrets.AZURE_RG }} \
          --template-file bicep/main.bicep \
          --parameters @bicep/parameters/dev.parameters.json